import Head from 'next/head'
import Button from '@mui/material/Button';
import Image from 'next/image'
import slider from '../img/slider.png'
import AboutIndex from './component/AboutIndex'
import ServiceIndex from './component/ServiceIndex'
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';

export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="home">
        <Swiper
          spaceBetween={50}
          slidesPerView={1}
          onSlideChange={() => console.log('slide change')}
          onSwiper={(swiper) => console.log(swiper)}
        >
          <SwiperSlide>
            <div className='SlidingImg'>
              <div className='ContentSlider'>
                <p>خانه یعنی زندگی، آن را زیباتر کنیم</p>
                <p>
                  با متخصصین طراحی دکوراسیون داخلی مشورت کنید
                </p>
                <Button sx={{ background: "#E9212E", color: "#fff" }}>
                  ثبت درخواست مشاوره رایگان
                </Button>
              </div>
              <Image src={slider}></Image>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <Image src={slider}></Image>
          </SwiperSlide>
          <SwiperSlide>
            <Image src={slider}></Image>
          </SwiperSlide>
        </Swiper>
      </div>
      <AboutIndex />
      <ServiceIndex / >
    </main>
  )
}
